const mongoose = require('mongoose');

const personalInfoSchema = new mongoose.Schema({
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    },
    lastName: { type: String },
    firstName: { type: String },
    middleName: { type: String },
    dateOfBirth: { type: Date },
    age: { type: Number },
    ssn: { type: String },
    dlOrIdNumber: { type: String },
    stateIssued: { type: String },
    revokedOrSuspendedDate: { type: Date },
    address: { type: String },
    city: { type: String },
    state: { type: String },
    zip: { type: String },
    homePhone: { type: String },
    workPhone: { type: String },
    gender: { type: String },
    race: { type: String },
    nationality: { type: String },
    maritalStatus: { type: String },
    usCitizen: { type: Boolean },
    residencyNumber: { type: String },
    primaryLanguageSpoken: { type: String },
    referredBy: { type: String },
    highestGradeCompleted: { type: Number },
    yearGraduated: { type: String },
    collegeHoursCompleted: { type: Number },
    degree: { type: String },
    employment: {
        isEmployed: { type: Boolean },
        employmentType: { type: String },
        employer: { type: String },
        occupation: { type: String },
        hourlyIncome: { type: Number },
        payFrequency: { type: String },
        specialSkills: { type: [String] },
    },
    history: {
        substanceAbuseTreatment: { type: Boolean },
        substanceAbuseTreatmentDetails: {
            where: { type: String },
            when: { type: Date },
        },
        mentalHealthTreatment: { type: Boolean },
        mentalHealthTreatmentDetails: {
            where: { type: String },
            when: { type: Date },
        },
        previousHelpFromDSM: { type: Boolean },
        previousHelpDetails: { type: Date },
        suicidalThoughts: { type: Boolean },
        arrestHistory: { type: Boolean },
        criminalJusticeInvolvement: { type: Boolean },
        criminalJusticeDetails: {
            incarcerationDate: { type: Date },
            charge: { type: String },
            location: { type: String },
            upcomingCourtDates: { type: String },
            probationOfficer: {
                name: { type: String },
                number: { type: String },
            },
        },
        alcoholUse: { type: Boolean },
        drugUse: { type: Boolean },
        drugPreference: { type: String },
        lastUse: { type: Date },
    },
    healthCare: {
        medicaid: { type: Boolean },
        medicare: { type: Boolean },
        privateInsurance: { type: Boolean },
        veteransBenefits: { type: Boolean },
        none: { type: Boolean },
    },
    medicalConditions: { type: [String] },
    medications: { type: [String] },
    reasonForAdmission: { type: [String] },
    goals: { type: String },
    talentsAndGifts: { type: [String] },
    emergencyContacts: [
        {
            name: { type: String },
            address: { type: String },
            phone: { type: String },
            alternatePhone: { type: String },
            relationship: { type: String },
        },
    ],
});

const PersonalInfo = mongoose.model('PersonalInfo', personalInfoSchema);

module.exports = PersonalInfo;
